FROM node:18-buster-slim

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm install --quiet --no-progress

COPY . ./
EXPOSE 34
CMD ["npm", "start"]